name: Lint
on:
  - push
  - pull_request
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phplint, laravel/pint
      - name: Check syntax
        run: phplint .
      - name: Check code style
        run: pint --test
