name: PHP-CS-Fixer

on: [push, pull_request]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run php-cs-fixer
        uses: docker://oskarstark/php-cs-fixer-ga

      - name: Commit php-cs-fixer changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.5
        with:
          commit_message: apply php-cs-fixer changes
          branch: ${{ github.head_ref }}
